### ISSUE TITLE
option 3 if multiple devices are in area, all devices start playing different music

### ISSUE THREAD

**Issue by LaneaLucy** [music-assistant/voice-support#101]
like the titel say. script should check if players can be synchronized, if yes, do so and play on group, if no, select one, not all

**Comment by nikito** [comment]
This night be a bit advanced for the use case of these scripts. Their main focus is finding music and requesting to play it on s targeted player or area. Having it figure out if an area has more than one speaker, if those speakers can sync, and going off on it's own and making a sync group first and then playing to it might be a bit much, and not sure if it's technically possible with what is exposed on the entities. Not sure how others have their players set up, but I've seen that name people would have these multiple players in a player group, and either target that in their command or have just that grip assigned to the area, though i know that's not necessarily ideal for everyone. 
I don't have enough players assigned to a single area to really test this unfortunately, but maybe some kind soul would like to take a swing at this scenario and open a mr? 🙂

**Comment by SteveDinn** [comment]
I ended up adding some templating logic to the script that is probably specific to me.

Firstly I ensure that all the media players in HA are tagged according to their function. Any that are meant for playing music, are labeled with "music". All my Google home minis are labeled with "Google home".

If the user specifies a particular player, then filter it against the list of players labeled with one of those labels, preferring music over Google home. 

If the user specified an area, it will look in that area for the first music player then for a Google home is there are no music players. 

Finally, if it can't discern a player, it'll ask the user to clarify.

**Comment by jherby2k** [comment]
I've got this issue as well. Ideally it wouldn't try to play on speakers that are hidden from the UI (these are voice assistants - i use these as announcement speakers, so they're in MA but not intended for playback)

**Comment by RamyBuilds** [comment]
Adding a write-up since I hit exactly this (speakers that expose several protocols at once), solved it, and a couple of people upthread asked the follow-up question — "how do I get a *default* speaker per room once I've stopped using area targeting?"

**Versions:** Home Assistant `2026.7.2`, Music Assistant server `2.9.9` (schema 31), MA integration as shipped in core, plus a vendor-specific custom integration (WiiM `1.0.95`) for the speakers that have a local HTTP API.

---

## 1. Why area targeting fans out

The bug isn't really "multiple devices in an area". It's **one physical speaker showing up as several MA players**, because each protocol it speaks gets discovered independently. Here's the census from my own server for a *single* room, with names genericised:

| MA provider | Player name | Available |
|---|---|---|
| `airplay` | `Living Room` | no |
| `chromecast` | `Living Room Pair` | yes |
| `universal_player` | `Living Room ` (note trailing space) | no |
| `universal_player` | `Living Room Speaker Left` | no |
| `universal_player` | `<Vendor>_<Model>_<serial>,` (raw mDNS name, trailing comma and all) | yes |
| `hass_players` | `Living Room Speaker Right` | yes |

Six MA players, four protocols, **one** stereo pair on the wall. Server-wide I have 51 player configs and every one of them is `enabled: true` by default. So when a voice command targets the area, the script enumerates all the members and starts an independent queue on each — hence three tracks at once.

Two aggravating factors worth knowing about:

- `universal_player` and `sync_group` entries **also** count as area members, so they double-count hardware you've already got covered by a real provider.
- Discovery names are not stable. The trailing space and the raw mDNS name above are both real entries that no amount of area-based matching will ever tidy up.

## 2. Things I tried that don't work

- **`homeassistant: → customize: → default_speaker:`** — I had this in `configuration.yaml` for a while. `default_speaker` is **not a real HA attribute**. Nothing reads it, so it silently does nothing. It shows up in enough forum posts that it's worth naming explicitly.
- **Disabling the extra protocol providers wholesale.** Tempting, but AirPlay/Chromecast are what my phones, laptops and TV actually use for other things. Turning off a provider to fix voice breaks unrelated playback.
- **Targeting the vendor's "group master" entity.** Some multiroom integrations only create a `..._group_master` entity *while* the speaker is the multiroom master, and key it by IP. Mine went master → solo one night; the entity went unavailable, MA dropped the player, and every music script broke silently — `music_assistant.play_media` has no `continue_on_error`, so the script aborted after switching inputs and the room just went quiet. Don't build on those.
- **Hoping MA picks a winner.** It can't, reasonably. It has no way to know that six players are one speaker.

## 3. What actually worked: stop targeting areas, map rooms to one entity each

I moved to local custom intents plus an explicit **room → single entity** table. This is the bit that answers "how do I get a default speaker per room": you don't need one, because you never enumerate an area. You look the room up.

A YAML anchor in `scripts.yaml`, so the table exists once and every script shares it:

```yaml
# ============== SHARED DEFINITIONS (YAML Anchors) ==============
.speaker_mapping: &speaker_mapping
  living_room: media_player.living_room_speaker_right_3
  bedroom:     media_player.bedroom_3
  kitchen:     media_player.kitchen_2
  hallway:     media_player.hallway_speaker_2
  office:      media_player.office_respeaker_media_player_2
  garden:      media_player.garden_airplay
  "whole house": media_player.chrome_home
```

Two notes on the right-hand side:

- These are deliberately the **MA mirror** entities (the `_2` / `_3`-suffixed ones that MA's `hass_players` provider creates), not the underlying integration entities. Pick one and be consistent — you'll get both, and they are not interchangeable.
- One room gets an AirPlay player and one gets a Chromecast, on purpose: pick per room whichever protocol is actually reliable there, instead of arguing with discovery.

Two mechanical points about the anchors, because they'll bite you otherwise: the keys start with a **dot** (`.speaker_mapping`, `.area_aliases`) so HA skips them instead of trying to load them as scripts, and YAML anchors are resolved top-down within a single file — both anchor blocks must sit **above** their first `*reference`, in the same file. They can't be shared across `scripts.yaml` and `automations.yaml`.

Then the resolution logic in the script:

```yaml
play_audio_intent:
  alias: Play Audio Intent
  mode: single
  fields:
    query: {}
    area: {}
    preferred_area_id: {}
    media_type: {}
  sequence:
    - variables:
        area_aliases: *area_aliases
        speaker_mapping: *speaker_mapping
        raw_area: "{% if area is defined and area != '' %}{{ area | lower | trim }}{% else %}{% endif %}"
        # preferred_area_id is the satellite's area slug (e.g. "bedroom"), resolved by HA
        # from the assist_satellite entity before the intent is dispatched.
        target_area: >-
          {% if raw_area != '' %}
            {{ area_aliases[raw_area] if raw_area in area_aliases else raw_area }}
          {% elif preferred_area_id is defined and preferred_area_id != '' %}
            {{ preferred_area_id }}
          {% else %}
            living_room
          {% endif %}
        speaker: >-
          {% set key = target_area | lower | trim %}
          {% if key in speaker_mapping %}
            {{ speaker_mapping[key] }}
          {% else %}
            media_player.living_room_speaker_right_3
          {% endif %}
```

Precedence is: **spoken room → satellite's own area → hardcoded fallback.** So "play X" on the bedroom satellite plays in the bedroom; "play X in the kitchen" from anywhere plays in the kitchen; and there is always exactly one entity at the end.

The `intent_script.yaml` side just forwards the slots:

```yaml
PlayAudio:
  description: "Play music. query is the song/artist/album name, area is optional room name"
  action:
    - action: script.play_audio_intent
      data:
        query: "{{ query }}"
        area: "{{ area | default('') }}"
        preferred_area_id: "{{ preferred_area_id | default('') }}"
  speech:
    text: "Playing {{ query }}"
```

This also covers the "don't play on my announcement-only satellites" case from upthread — a player that isn't in the table is never a candidate, whether or not it's hidden in the UI.

If you'd rather shrink the pool as well as ignore it, MA does expose a per-player `enabled` flag (Settings → Players), so you can switch off the redundant protocol duplicates. I left mine all enabled and let the map do the work, so I can't claim that path is trouble-free — just that the flag is there.

## 4. `preferred_area_id` gotchas

This is the useful, under-documented bit, so a few warnings:

- **`device_id` and `satellite_id` are *not* available in `intent_script` templates.** This is the wall most people hit when trying to work out which satellite spoke. `preferred_area_id` is what you get, and it's a **slug** (`living_room`), not a friendly name.
- It's injected by the **built-in** Assist agent when it matches your custom sentences. If an LLM agent handles the utterance instead, expect it to be empty — hence the `| default('')` and the explicit fallback above. Don't treat it as guaranteed.
- **The satellite's HA area assignment must match the physical room.** That mapping is now load-bearing: get it wrong and music comes out of the wrong room with no error anywhere.
- If your satellites are ESPHome, **never rename the node `name:`** once this is wired up — entity IDs derive from it and the table breaks silently. Rename `friendly_name` only.

## 5. Normalise room names in two places

STT is a much bigger source of "wrong room" than the config is. Mine reliably mishears room names, so aliases exist at both layers.

In `custom_sentences/en/media.yaml`, using list `in`/`out` so the intent receives a canonical value:

```yaml
language: "en"
lists:
  area:
    values:
      - in: "living room"
        out: "living room"
      - in: "loving room"     # genuinely what the STT returns, often
        out: "living room"
      - in: "lounge"
        out: "living room"
      - in: "front room"
        out: "living room"
      - in: "the lounge"
        out: "living room"
```

...and again as the `&area_aliases` dict referenced above, mapping spoken forms to **area slugs**, which is what catches anything arriving from a different path:

```yaml
.area_aliases: &area_aliases
  "living room": "living_room"
  "lounge": "living_room"
  "sitting room": "living_room"
  "bedroom": "bedroom"
  "kitchin": "kitchen"
  "kitchen": "kitchen"
  "hall": "hallway"
  "corridor": "hallway"
  "study": "office"
  "patio": "garden"
  "everywhere": "whole house"
  "all speakers": "whole house"
```

Before blaming your intent or MA for a wrong-room bug, check the raw STT text — via the websocket API, `assist_pipeline/pipeline_debug/list` then `/get` will show you `stt_output` as it actually arrived.

## 6. Four more traps, all specific to multi-protocol setups

**Never pass raw spoken text to `music_assistant.play_media`.** MA takes its own top search hit, which in my case was very often an unplayable Bandcamp artist page: queue loads zero items, "No playable items found", room goes silent, no error surfaced to the user. Search first and rank the candidates yourself:

```yaml
    - action: music_assistant.search
      data:
        config_entry_id: YOUR_MA_CONFIG_ENTRY_ID # see §6 re: duplicate entries
        name: "{{ query }}"
      response_variable: search_result
      continue_on_error: true
    - variables:
        # Local library first (always playable), then the streaming provider,
        # then any other scheme. Bare http(s) results are rejected outright —
        # they are the ones that produced the silent failures.
        resolved_uri: >-
          {% set mt = (media_type | default('')) | trim %}
          {% set groups = {'artist': 'artists', 'album': 'albums',
                           'track': 'tracks', 'playlist': 'playlists',
                           'radio': 'radio'} %}
          {% set keys = [groups[mt]] if mt in groups
                        else ['tracks', 'albums', 'artists', 'playlists', 'radio'] %}
          {% set ns = namespace(best='', score=99) %}
          {% for k in keys %}
            {% for item in (search_result | default({})).get(k) or [] %}
              {% set uri = item.uri | default('') %}
              {% set score = 0 if uri.startswith('library://')
                        else 1 if 'tidal' in uri
                        else 2 if uri and not uri.startswith('http')
                        else 99 %}
              {% if score < ns.score %}
                {% set ns.score = score %}
                {% set ns.best = uri %}
              {% endif %}
            {% endfor %}
          {% endfor %}
          {{ ns.best if ns.score < 99 else '' }}
```

If nothing resolves, announce that on the satellite rather than starting playback — otherwise you get a room that reports "playing" into silence.

**MA 2.9.9 added a per-user `player_filter`.** After updating, my main MA user had an explicit player allow-list that still named a dead entity and omitted the live one. Symptom: `user does not have access to player <name>`, and the HA entity sits there as `restored: true` looking merely unavailable. Two things to know — check `auth/users` → `player_filter` *first* whenever a player looks unavailable in HA but healthy on the MA server; and **permission changes only take effect after reloading the HA config entry**, because the client caches them at connect time.

**Check for duplicate MA config entries.** I had two entries pointing at the same server. They collided on unique IDs (`Platform music_assistant does not generate unique IDs ... already exists - ignoring`) for five players and reshuffled entity ownership on every restart, which looks exactly like a flaky speaker. Disabling the spare entry (reversible) fixed it.

**MA sync groups may reuse the vendor's own multiroom mechanism.** On my hardware a speaker can only be in one group at a time, so when MA called `set_members` to build a whole-house group and included one half of a stereo pair, it tore the pair down and nothing re-formed it. If your speakers do vendor multiroom, grep the MA server log for `set_members` when a pair mysteriously splits, and consider an automation that heals the pair when the master's role drops to solo.

---

**tl;dr for anyone landing here:** the fix isn't smarter area handling, it's not using areas as the target at all. Keep an explicit `room → one entity` table, resolve it from the spoken room first and `preferred_area_id` second, and keep a hardcoded fallback. Ten lines of Jinja, and it can't fan out because there is only ever one entity in the target.
