### ISSUE TITLE
Error: UndefinedError: 'None' has no attribute 'split'

### ISSUE THREAD

**Issue by lich2000117** [music-assistant/voice-support#58]
The automation seems failed using option 2.

At stage:
alias: Store relevant part of LLM result in variable and define target

Not sure if there's anything wrong with my config.

Can confirm LLM GPT works as a conversation agent, with Assist access.

Also my music assistant seems exposed my speaker, as well as home assistant's own media player integration.

![image](https://github.com/user-attachments/assets/a2db6d52-9563-40b8-8461-0a27e3aebbeb)

Thank you in advance!

**Comment by lich2000117** [comment]
Also to add, when I type prompt in home assistant assist, it shows "Done" instantly, already configured prefer cloud connection

**Comment by nikito** [comment]
What does the trace of the automation look like?

**Comment by TheFes** [comment]
I would need to see a trace to determine what is going wrong. You can download the full trace in json using the download button in the top right corner.

The selector should indeed only show Music Assistant media player entities, as it filters on that integration.
```yaml
        default_player:
          name: Default Player
          description:
            "The default Music Assistant player which will be used in case
            it is not clear from the request in which area or on which player the
            request should be played

            Leave empty in case you do not want a default player"
          selector:
            entity:
              filter:
                - integration: music_assistant
                  domain:
                    - media_player
```

BTW, if you're LLM is allowed to use Assist, I would recommend using option 3.
