### ISSUE TITLE
Assist telling me that music is played & nothing happens.

### ISSUE THREAD

**Issue by hhopke** [music-assistant/voice-support#63]
Hi guys,

I am facing to problems:

1. Feedback of LLM is wrong. Output: "I am playing ...." instead of failed to play out of what ever reason.
2. When executing the script via LLM it's not working where as if I enter same details and click on execute it does play. The odd thing is that it used to work though not sure when it stopped working. 

**system:**
Core 2025.2.4
Supervisor 2025.02.1
Operating System 14.2
Frontend 20250214.0

**Script:** LLM Script for Music Assitant voice requests

```variables:
  default_player: media_player.kuche_2
  player_data: >-
    {% set ma = integration_entities('music_assistant') %}

    {% set ma_names = ma | map('state_attr', 'friendly_name') | list %}

    {% set ns = namespace(players=[]) %} {% for player in media_player |
    default([], true) %}

    {% if player in ma %}

    {% set ns.players = ns.players + [player] %}

    {% elif player in ma_names %}

    {% set entity = ma | select('is_state_attr', 'friendly_name', player) | list
    %}

    {% set ns.players = ns.players + entity %}

    {% endif %}

    {% endfor %}

    {{ ns.players }}
  target_data:
    area_id: '{{ area | default(''NA'', true) }}'
    entity_id: >-
      {{ 'NA' if area | default and not player_data else (player_data or
      default_player) | default('NA', true) }}
  invalid_target:
    response: Unable to find valid target```

**Comment by nikito** [comment]
Does the script trace show anything when asking llm for music? Script is still exposed and still has it's description? And what llm is being used?

**Comment by pducos** [comment]
I am having the same issue, using Open AI LLM and it works great with everything else. Music Assistant is installed properly, the music server works and it plays music on the device when doing manually.

The script blueprint is installed and the created script is exposed the the AI. The response makes it seem like the AI executed properly but like the previous person it shows unable to find target. Like if it cant find any media devices to play.

```
this:
  entity_id: script.llm_music
  state: 'off'
  attributes:
    last_triggered: '2025-02-23T12:13:04.445246+00:00'
    mode: parallel
    current: 0
    max: 10
    friendly_name: 'llm : music'
  last_changed: '2025-02-23T12:13:04.448961+00:00'
  last_reported: '2025-02-23T12:13:04.448961+00:00'
  last_updated: '2025-02-23T12:13:04.448961+00:00'
  context:
    id: 01JMSBK76KMXRH774EXQW1EZDB
    parent_id: null
    user_id: null
media_type: artist
artist: Taylor Swift
album: ''
media_id: Taylor Swift
media_description: Taylor Swift's music
area:
  - playroom
context:
  id: 01JMSBPW9FSSQ27PX7QG384Y6C
  parent_id: null
  user_id: null
version: 20250128
default_player: null
player_data: []
target_data:
  area_id:
    - playroom
  entity_id: NA
invalid_target:
  response: Unable to find valid target
```

**Comment by nikito** [comment]
The above is actually normal, it located the area which is playroom. Anything else in the trace? Any errors in MA log?

**Comment by pducos** [comment]
[d5369777_music_assistant_2025-02-23T16-33-18.068Z.log](https://github.com/user-attachments/files/18931735/d5369777_music_assistant_2025-02-23T16-33-18.068Z.log)

No errors I can see, from the timeline there was an error with the youtube music cookie, but i fixed that. After 11:33 there are no more errors.

**Comment by nikito** [comment]
Hmm lots of errors around it, maybe restart HA and see if that clears things out? May want to see what the script sent to the service call in the trace as well.

**Comment by pducos** [comment]
I uninstalled, the server and the addon. Cleared all data. Rebooted home assistant. Reinstalled the server, reinstalled the addon. Added the service provider and the speaker again. Still it does not play. You are correct that it finds the target area, but the entity_id is NA, maybe that is why it wont play?

Here is the logs of Music Assistant, and the trace of the voice script

[d5369777_music_assistant_2025-02-23T17-11-12.036Z.log](https://github.com/user-attachments/files/18932008/d5369777_music_assistant_2025-02-23T17-11-12.036Z.log)

```
this:
  entity_id: script.llm_music
  state: 'off'
  attributes:
    last_triggered: '2025-02-23T17:07:45.953591+00:00'
    mode: parallel
    current: 0
    max: 10
    friendly_name: 'llm : music'
  last_changed: '2025-02-23T17:07:45.957003+00:00'
  last_reported: '2025-02-23T17:07:45.957003+00:00'
  last_updated: '2025-02-23T17:07:45.957003+00:00'
  context:
    id: 01JMSWDKDWHWR7WQM22RK825PE
    parent_id: null
    user_id: null
media_type: track
artist: Linkin Park
album: ''
media_id: Emptiness Machine
media_description: Emptiness Machine by Linkin Park
area:
  - playroom
context:
  id: 01JMSWHAFE4JZ51K1PWWACPRBR
  parent_id: null
  user_id: null
version: 20250128
default_player: null
player_data: []
target_data:
  area_id:
    - playroom
  entity_id: NA
invalid_target:
  response: Unable to find valid target
```
