### ISSUE TITLE
Option 3 - media_description appears to be unused

### ISSUE THREAD

**Issue by CashWilliams** [music-assistant/voice-support#64]
I can't see where `media_description` is used in the script, though it is defined as a input and the LLM populates it.

Sample call for "play 10 classic rock songs".

From the script debug, for the variables changed on the first step:
```
this:
  entity_id: script.music_assistant_voice_requests
  state: 'off'
  attributes:
    last_triggered: '2025-02-24T00:23:56.826687+00:00'
    mode: parallel
    current: 0
    max: 10
    friendly_name: Music Assistant voice requests
  last_changed: '2025-02-24T00:23:57.923189+00:00'
  last_reported: '2025-02-24T00:23:57.923189+00:00'
  last_updated: '2025-02-24T00:23:57.923189+00:00'
  context:
    id: 01JMTNDE6Q15AB1YE7F0WG9TD1
    parent_id: null
    user_id: null
media_type: track
artist: ''
album: ''
media_id: classic rock
media_description: 10 classic rock songs
area:
  - office
context:
  id: 01JMTNT1TJDP7J6CRM9S23EJCM
  parent_id: null
  user_id: null
version: 20250128
default_player: media_player.office_sonos
player_data: []
target_data:
  area_id:
    - office
  entity_id: NA
invalid_target:
  response: Unable to find valid target
```

But resulting call to the action in the last step is:

```
params:
  domain: music_assistant
  service: play_media
  service_data:
    media_id: classic rock
    media_type: track
    area_id:
      - office
  target:
    area_id:
      - office
running_script: false
```

This results in only 1 song getting added to the queue always.
