### ISSUE TITLE
[Option 3] "Invalid literal for int() with base 10" when playing via script

### ISSUE THREAD

**Issue by Californian** [music-assistant/voice-support#69]
When I try to get any voice assistant (google, claude, chatgpt) to play music via the "option 3" LLM script, I get this error: `ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_media: invalid literal for int() with base 10: '451GvHwY99NKV4zdKPRWmv'`

The specific string (`451GvHwY99NKV4zdKPRWmv`) is the Spotify ID of the track, but beyond that I'm not sure how it's being used or why there's an attempt to convert it into an `int`.

Any ideas what's going on or how I can attempt to debug?

**Comment by Californian** [comment]
It looks like it's due to the `radio_mode` field, removing it fixes the issue. I'll put up a PR for this shortly.

**Comment by nikito** [comment]
Not sure a pr would make sense for that, considering other people use radio mode and it works. It should work as long as the provider supports radio mode. Should probably figure out what about that field is causing an issue 🤔

**Comment by Californian** [comment]
Ha yes I came here to say that -- the issue doesn't lie in this repo at all, but rather in the main music_assistant one (or maybe the HA integration). You can reproduce it with the following action in HA:
```yaml
action: music_assistant.play_media
target:
  entity_id: [any MA media player]
data:
  media_id: Banana Pancakes [or any other track name]
  media_type: track
  radio_mode: true
```
