### ISSUE TITLE
Option to disallow "media_player.this_device" on satellite

### ISSUE THREAD

**Issue by jose1711** [music-assistant/voice-support#81]
Using HA Voice PE with no external speakers connected (and no plan to do so). When I ask it to play music, the following is sent to MA:
```
params:
  domain: music_assistant
  service: play_media
  service_data:
    media_id: metallica
    media_type: artist
    entity_id:
      - media_player.this_device
  target:
    entity_id:
      - media_player.this_device
```
Instead of "this_device" I would like to play it on my default player.
