### ISSUE TITLE
Cast devices can turn off in the background while Music Assistant thinks they're still paused. They then can't be resumed.

### ISSUE THREAD

**Issue by SteveDinn** [music-assistant/voice-support#90]
When you've exposed a Google Cast-based media player in Music Assistant to Home Assistant, I've found that if left paused for an extended period (it varies per device, but my Google Home Minis only last 10 minutes while paused) will go into an `idle` state or just turn off altogether. Once they're not in a `paused` state anymore, my Conversation agent doesn't know what to do when I ask it to resume those players.

I've written a Home Assistant script to handle this case where the player is paused, but not paused.
```
alias: Resume Playing Music Assistant Speaker
description: >-
  When the user asks to resume playing on a speaker, this script should be run
  instead of trying to resume playing by directly affecting a particular device.
mode: parallel
max: 10
fields:
  media_player_name:
    selector:
      text:
        multiple: false
        multiline: false
    description: >-
      The name of the media_player device to resume. Remove any articles like
      'the' or 'a' which might be a prefix or suffix to the name.
    name: Media Player
sequence:
  - variables:
      media_player_entity: |-
        {{ integration_entities('music_assistant') 
          | expand 
          | selectattr('name', 'search', media_player_name, ignorecase=True)
          | map(attribute='entity_id') 
          | first
          | default }}
  - alias: >-
      If we couldn't find a music-assistant player, then check for other types
      of media_player
    if:
      - condition: template
        value_template: "{{ media_player_entity | length == 0 }}"
    then:
      - variables:
          media_player_entity: |-
            {{ states.media_player
              | selectattr('attributes.friendly_name', 'search', media_player_name, ignorecase=True)
              | map(attribute='entity_id') 
              | first
              | default }}
      - alias: If we can't find *any* matching media_player entity, then stop.
        if:
          - condition: template
            value_template: "{{ media_player_entity | length == 0 }}"
        then:
          - stop: >-
              A media player matching the name of {{ media_player_name }} could
              not be found.
            response_variable: response
      - action: media_player.media_play
        metadata: {}
        data: {}
        target:
          entity_id: "{{ media_player_entity }}"
      - stop: Resuming {{ media_player_name }}
        response_variable: response
  - alias: If the player is off, then turn it on.
    if:
      - condition: template
        value_template: "{{ states(media_player_entity) in ['off'] }}"
    then:
      - action: media_player.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: "{{ media_player_entity }}"
  - alias: If the player does not have music-assistant attributes, stop.
    if:
      - condition: template
        value_template: >-
          {{ state_attr(media_player_entity, 'app_id') | lower !=
          'music_assistant' }}
    then:
      - stop: "{{ media_player_name }} does not have music assistant attributes"
        response_variable: response
  - alias: If the player is idle or paused, then press play.
    if:
      - condition: template
        value_template: "{{ states(media_player_entity) in ['playing', 'idle'] }}"
    then:
      - action: media_player.media_play
        metadata: {}
        data: {}
        target:
          entity_id: "{{ media_player_entity }}"
  - stop: Resuming music on {{ media_player_name }}
    response_variable: response
```
